[book]
authors = ["Adam Chalmers"]
language = "en"
multilingual = false
src = "src"
title = "Modeling with KCL"

[preprocessor.kcl]
command = "mdbook-kcl"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/KittyCAD/kcl-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/KittyCAD/kcl-book/edit/main/guide/{path}"
site-url = "/docs/kcl-lang/"

[output.html.code.hidelines]
kcl = "#"

# [output.linkcheck]

# [output.pdf]

# [output.html.print]
# enable = true
